### Registration
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "username": "gunkim",
    "password": "test",
    "email": "gunkim.dev@gmail.com"
  }
}

### Authentication
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "gunkim.dev@gmail.com",
    "password": "test"
  }
}

### Get Current User
GET http://localhost:8080/api/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiJmZjFjY2UzNC01ZGQxLTQ3YzYtYjBiMi04ZjdkMTUxMGY2ZDciLCJpYXQiOjE3MjQxMjAzODEsImV4cCI6MTcyNDEyMjE4MX0.cvF-_9t26iadMrSBQF4A-n47CGC4vRlVMU0PTiW4PeThqN5HJoJUe2ZIGyeuKE0M79qIAF_JOSYfu0AOl01tcanbClFDZ1-kC6hD0VYGJ44wj13L2ApCkyshHuHg7umJ4jyRw_Km9Dqtf5TPuNPStVNS6xysH2h5pVGBrzHA_nP4HA3jmb6PJ2FUwUWm0sirUWPAUX4400XytnDUQi5qemMPUdcbyYGtytLWDGeAoPau2o5T6VyGRz0LeGxw5QIHt1lFFpQwEXyMsmV-Ftz3a0WUc7qSH2XxGCUCJJG1NC68fHRw6S3RIy-qqYh6Rsn5tb9yS9vUnav8jJ0mmHTyAg

### Update User
PUT http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiJmZjFjY2UzNC01ZGQxLTQ3YzYtYjBiMi04ZjdkMTUxMGY2ZDciLCJpYXQiOjE3MjQxMjAzODEsImV4cCI6MTcyNDEyMjE4MX0.cvF-_9t26iadMrSBQF4A-n47CGC4vRlVMU0PTiW4PeThqN5HJoJUe2ZIGyeuKE0M79qIAF_JOSYfu0AOl01tcanbClFDZ1-kC6hD0VYGJ44wj13L2ApCkyshHuHg7umJ4jyRw_Km9Dqtf5TPuNPStVNS6xysH2h5pVGBrzHA_nP4HA3jmb6PJ2FUwUWm0sirUWPAUX4400XytnDUQi5qemMPUdcbyYGtytLWDGeAoPau2o5T6VyGRz0LeGxw5QIHt1lFFpQwEXyMsmV-Ftz3a0WUc7qSH2XxGCUCJJG1NC68fHRw6S3RIy-qqYh6Rsn5tb9yS9vUnav8jJ0mmHTyAg

{
  "user": {
    "email": "jake@jake.jake",
    "bio": "I like to skateboard",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

###
GET http://localhost:8080/api/profiles/gunkim
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiJmZDMyYTI5ZC04MWM2LTQ3ZjgtYmUwYy1iYTY3NzdkZjVhYWUiLCJpYXQiOjE3MjQ1NjEzNjIsImV4cCI6MTcyNDU2MzE2Mn0.CTY3W-8-7l2YrzLaO5Z2G59OJEICuDs27sLAb55kHtE_nI5BCsg8mVAcG_rRJBSvjCZlCIKmBCEzaxjNZx6Nf9n5eax4SplPKh1JxxfKdtTFLsrxGnW5gvvPpkkTAK8F3fa7UO9__Mx6XrqghWseKWdjxlFHhJoQIZe2ijlOlwA2ayZO2CkNeli8pfZ_I3rTKnuj0aNvsBKgJLC1LKBD-tMzEK4q98aKS4cUVJatKqpeHfy_XI6UEai4UnNel6I63EZmBF8YgxpE_jViMgJ0e9dvko0_Na9MG0c4q9ifRoCx5wxSIvE9lJYi1MYh75pxW0OEexrSqLD5E5KMVsBQvw
