### Registration
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "username": "gunkim",
    "password": "test",
    "email": "gunkim.dev@gmail.com"
  }
}

### Authentication
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "gunkim.dev@gmail.com",
    "password": "test"
  }
}

### Get Current User
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiJjZDM5NTBiOC03ZmRmLTRkMzgtYjQ2OS03OWIzNjhmM2NlOTMiLCJpYXQiOjE3MjQ3MTgwNjcsImV4cCI6MTcyNDcxOTg2N30.kFw60Ox99fS_vUPnqwknxbH1c_MJ8kRRAYVLbfcAHVCOyG2yH0uF-jhaP2ks0Xb3gNp-tHB9uqEAaXvFeSjkU6tJI-LJcFjpK75HN4mZ_qJwKbi-C_o2wl5JhA0Mv3T3XuCkfMTEIXnIGCnp9AjQXbt4OrAcYpNd0RRgoW2_XWwpirchyz44lC2TQs7g_Q74S_qJ3VuqL4VVWh75LV22RfRrVV-K1qwF7vpjN6MK378ogr9i7F7SAxQEiDSlwfyejgMcXv9r9jReLn00ewxweVJzb1j1SXWwLK7SiZEKfBQBw6QcMoDOm6LMw9X0ldLq_fIkHSLOhBaYWAi3CVAWug

### Update User
PUT http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiJmZjFjY2UzNC01ZGQxLTQ3YzYtYjBiMi04ZjdkMTUxMGY2ZDciLCJpYXQiOjE3MjQxMjAzODEsImV4cCI6MTcyNDEyMjE4MX0.cvF-_9t26iadMrSBQF4A-n47CGC4vRlVMU0PTiW4PeThqN5HJoJUe2ZIGyeuKE0M79qIAF_JOSYfu0AOl01tcanbClFDZ1-kC6hD0VYGJ44wj13L2ApCkyshHuHg7umJ4jyRw_Km9Dqtf5TPuNPStVNS6xysH2h5pVGBrzHA_nP4HA3jmb6PJ2FUwUWm0sirUWPAUX4400XytnDUQi5qemMPUdcbyYGtytLWDGeAoPau2o5T6VyGRz0LeGxw5QIHt1lFFpQwEXyMsmV-Ftz3a0WUc7qSH2XxGCUCJJG1NC68fHRw6S3RIy-qqYh6Rsn5tb9yS9vUnav8jJ0mmHTyAg

{
  "user": {
    "email": "jake@jake.jake",
    "bio": "I like to skateboard",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

###
GET http://localhost:8080/api/profiles/gunkim
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiIxMzEyNWEzOC01ZjUxLTRhYTAtYmFlNi0yYmEzZDFkYTU3M2YiLCJpYXQiOjE3MjQ3MTkzNTMsImV4cCI6MTcyNDcyMTE1M30.PZPUtK7YkpeNLC4vh2dkKPwLBPx2G7snKvJu4uiwkoU6il9e2vMpqxH3y6NrRYVCV9WajjH_VvjA-Xw-GsQDW-4Hod_bKDe1GhZ1XU11L70JakpQnXVzi9gJju85nUddkG5AsjRyjbkHdERS0Np_KBQc8HhA1RP1i2hLma6zkJ7cYxaj9ZUFK9thOhNbhR6VZv4px2PwWOwhQ_FObVU_NNY4N-2lDAi6hBsw0a-ipm2LAPYrEQVpDB6C91VIY2IS5uUkHpYoiUmElVmQ3LApZ7eCNzTjGCpHCmne8xofWyjehBye8mNbbMuzLWy14dmkadB62MBf9pOc79-oa2-wlw

###
POST http://localhost:8080/api/profiles/gunkim/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiIxMzEyNWEzOC01ZjUxLTRhYTAtYmFlNi0yYmEzZDFkYTU3M2YiLCJpYXQiOjE3MjQ3MTkzNTMsImV4cCI6MTcyNDcyMTE1M30.PZPUtK7YkpeNLC4vh2dkKPwLBPx2G7snKvJu4uiwkoU6il9e2vMpqxH3y6NrRYVCV9WajjH_VvjA-Xw-GsQDW-4Hod_bKDe1GhZ1XU11L70JakpQnXVzi9gJju85nUddkG5AsjRyjbkHdERS0Np_KBQc8HhA1RP1i2hLma6zkJ7cYxaj9ZUFK9thOhNbhR6VZv4px2PwWOwhQ_FObVU_NNY4N-2lDAi6hBsw0a-ipm2LAPYrEQVpDB6C91VIY2IS5uUkHpYoiUmElVmQ3LApZ7eCNzTjGCpHCmne8xofWyjehBye8mNbbMuzLWy14dmkadB62MBf9pOc79-oa2-wlw

###
DELETE http://localhost:8080/api/profiles/gunkim/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiIxMzEyNWEzOC01ZjUxLTRhYTAtYmFlNi0yYmEzZDFkYTU3M2YiLCJpYXQiOjE3MjQ3MTkzNTMsImV4cCI6MTcyNDcyMTE1M30.PZPUtK7YkpeNLC4vh2dkKPwLBPx2G7snKvJu4uiwkoU6il9e2vMpqxH3y6NrRYVCV9WajjH_VvjA-Xw-GsQDW-4Hod_bKDe1GhZ1XU11L70JakpQnXVzi9gJju85nUddkG5AsjRyjbkHdERS0Np_KBQc8HhA1RP1i2hLma6zkJ7cYxaj9ZUFK9thOhNbhR6VZv4px2PwWOwhQ_FObVU_NNY4N-2lDAi6hBsw0a-ipm2LAPYrEQVpDB6C91VIY2IS5uUkHpYoiUmElVmQ3LApZ7eCNzTjGCpHCmne8xofWyjehBye8mNbbMuzLWy14dmkadB62MBf9pOc79-oa2-wlw
