### Registration User 1
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "username": "gunkim",
    "password": "test",
    "email": "gunkim.dev@gmail.com"
  }
}
eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNWFkMWEzOC00MGE2LTQ3ZDItOWY1Yy0wNGU4YzI5MzJlNDciLCJpYXQiOjE3MzkyOTYwNDUsImV4cCI6MTczOTI5Nzg0NX0.JqbamrTyWqtyNMSq20XTLY_8-LHTp-5Nm3XyPGSj3OU

### Registration User 2
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "username": "gunkim1",
    "password": "test",
    "email": "gunkim.dev2@gmail.com"
  }
}
eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJjYmFmMjM2YS0zMDg2LTQzN2MtYWVkZi1jMTc0Mzk3ZTAwNjIiLCJpYXQiOjE3MzkyOTYwNTMsImV4cCI6MTczOTI5Nzg1M30.O_uV7tOj5kSDAFdCaST6xEhL67FJldP-7mRXxZBfCqs

### Authentication
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "gunkim.dev@gmail.com",
    "password": "test"
  }
}

### Get Current User
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJjYjlhNmFkOS1iODAxLTQ4OGMtOWM4ZS05OTkyNDRjOGMzMmYiLCJpYXQiOjE3MzkyOTUxOTAsImV4cCI6MTczOTI5Njk5MH0.30AM6wF65bQ5JCwQ894DKYtWrk0ij-8G0NdFQp0p3Xc

### Update User
PUT http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxNWFkMWEzOC00MGE2LTQ3ZDItOWY1Yy0wNGU4YzI5MzJlNDciLCJpYXQiOjE3MzkyOTYwNDUsImV4cCI6MTczOTI5Nzg0NX0.JqbamrTyWqtyNMSq20XTLY_8-LHTp-5Nm3XyPGSj3OU

{
  "user": {
    "email": "jake@jake.jake",
    "bio": "I like to skateboard",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

###
GET http://localhost:8080/api/profiles/gunkim
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJjYmFmMjM2YS0zMDg2LTQzN2MtYWVkZi1jMTc0Mzk3ZTAwNjIiLCJpYXQiOjE3MzkyOTYwNTMsImV4cCI6MTczOTI5Nzg1M30.O_uV7tOj5kSDAFdCaST6xEhL67FJldP-7mRXxZBfCqs

###
POST http://localhost:8080/api/profiles/gunkim/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJjYmFmMjM2YS0zMDg2LTQzN2MtYWVkZi1jMTc0Mzk3ZTAwNjIiLCJpYXQiOjE3MzkyOTYwNTMsImV4cCI6MTczOTI5Nzg1M30.O_uV7tOj5kSDAFdCaST6xEhL67FJldP-7mRXxZBfCqs

###
DELETE http://localhost:8080/api/profiles/gunkim/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJjYmFmMjM2YS0zMDg2LTQzN2MtYWVkZi1jMTc0Mzk3ZTAwNjIiLCJpYXQiOjE3MzkyOTYwNTMsImV4cCI6MTczOTI5Nzg1M30.O_uV7tOj5kSDAFdCaST6xEhL67FJldP-7mRXxZBfCqs
