version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: realworld-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: realworld
      MYSQL_USER: realworld
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../core-impl/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql-data: